ungrouped:
  hosts:
    # TODO
app_group:
  hosts:
    managedhost-app-1:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2223  # Should match the port mapping for managedhost-app-1 in docker-compose.yml
      ansible_user: root
    managedhost-app-2:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2224  # Should match the port mapping for managedhost-app-2 in docker-compose.yml
      ansible_user: root
    managedhost-app-3:
      ansible_host: 0.0.0.0
      ansible_connection: ssh
      ansible_port: 2225  # Should match the port mapping for managedhost-app-3 in docker-compose.yml
      ansible_user: root